version: 2

dependencies:
  - run:
      name: Download Dependencies
      command: ./gradlew androidDependencies

jobs:
  build-debug:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build assembleDebug
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build:
    jobs:
      - build-debug:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/