version: 2

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

dependencies:
  - run:
      name: Download Dependencies
      command: ./gradlew androidDependencies

jobs:
  build-stage:
      working_directory: ~/LolsumoStage

      docker:
        - image: circleci/android:api-27-alpha

      steps:
        - checkout

        - restore_cache:
            <<: *cache_key

        - run:
            name: Assemble
            command: ./gradlew assembleStaging
        - store_artifacts:
            path: app/build/outputs/apk

        - save_cache:
            <<: *cache_key
            paths:
              - ~/.gradle/caches
              - ~/.gradle/wrapper

workflows:
  version: 2
  build:
    jobs:
      - build-stage:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/